# Generated by Django 4.0.6 on 2023-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer')),
                ('type_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('name_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name_laptop')),
                ('link_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link_laptop')),
                ('price_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Price_laptop')),
                ('image_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
